defaults: &defaults
  working_directory: /tmp/api-router
  docker:
    - image: circleci/node:8

version: 2
jobs:
  setup:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      -run:
        name: Install Dependencies
        command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
          - node_modules/
      - persist_to_workspace:
        root: /tmp
        paths:
          - api-router/*
      - run:
        name: Lint
        command: npm test
